# articubot_one/config/bridge_ros2_control.yaml
# Top-level is a sequence ("- …")
- ros_topic_name: /clock
  gz_topic_name:  /clock
  ros_type_name:  rosgraph_msgs/msg/Clock
  gz_type_name:   gz.msgs.Clock
  direction:      GZ_TO_ROS        # read-only

- ros_topic_name: /cmd_vel
  gz_topic_name:  /cmd_vel
  ros_type_name:  geometry_msgs/msg/Twist
  gz_type_name:   gz.msgs.Twist    # bidirectional default

- ros_topic_name: /lidar2
  gz_topic_name:  /lidar2
  ros_type_name:  sensor_msgs/msg/LaserScan
  gz_type_name:   gz.msgs.LaserScan
  direction:      GZ_TO_ROS

# If using a non-depth sensing camera:
# - ros_topic_name: "/camera/camera_info"
#   gz_topic_name: "/camera/camera_info"
#   ros_type_name: "sensor_msgs/msg/CameraInfo"
#   gz_type_name: "gz.msgs.CameraInfo"
#   direction: GZ_TO_ROS
# - ros_topic_name: "/camera/image_raw"
#   gz_topic_name: "/camera/image_raw"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "gz.msgs.Image"
#   direction: GZ_TO_ROS

# If using a depth-sensing camera:
- ros_topic_name: "/camera/depth/image"
  gz_topic_name: "/camera/depth/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name:  "gz.msgs.Image"
  direction:     GZ_TO_ROS

- ros_topic_name: "/camera/depth/camera_info"
  gz_topic_name: "/camera/depth/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name:  "gz.msgs.CameraInfo"
  direction:     GZ_TO_ROS

- ros_topic_name: "/camera/depth/points"
  gz_topic_name:  "/camera/depth/points"
  ros_type_name:  "sensor_msgs/PointCloud2"
  gz_type_name:   "gz.msgs.PointCloudPacked"
  direction:      GZ_TO_ROS

# If using a depth AND rgb sensing camera:
# - ros_topic_name: "/camera/camera_info"
#   gz_topic_name: "/camera/camera_info"
#   ros_type_name: "sensor_msgs/msg/CameraInfo"
#   gz_type_name: "gz.msgs.CameraInfo"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/camera/image_raw"
#   gz_topic_name: "/camera/image_raw"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "gz.msgs.Image"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/camera/points"
#   gz_topic_name:  "/camera/points"
#   ros_type_name:  "sensor_msgs/PointCloud2"
#   gz_type_name:   "gz.msgs.PointCloudPacked"
#   direction:      GZ_TO_ROS