controller_manager:
  ros__parameters:               # ← double underscore is mandatory
    update_rate: 30              # [Hz] control loop
    use_sim_time: true

    # --- Controller plugins to be loaded ---------------------------
    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
      # optional broadcaster parameters
      publish_rate: 50.0

# -------------------------------------------------------------------
diff_cont:
  ros__parameters:
    # TF / odometry --------------------------------------------------
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true          # publish odom→base_link TF
    cmd_vel_timeout: 0.5          # [s] watchdog

    # Wheel geometry -------------------------------------------------
    left_wheel_names:  ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.35        # [m]
    wheel_radius:     0.05        # [m]

    # Behaviour ------------------------------------------------------
    publish_rate: 30.0            # [Hz] odom & TF throttling
    use_stamped_vel: false        # expect geometry_msgs/Twist on /cmd_vel_unstamped
    open_loop:        true        # ← avoids zero-feedback stall